=== gitoyen/peering/peers.dtd
<!--
     Copyright Stephane Bortzmeyer <bortzmeyer@gitoyen.net> 
  -->

<!ELEMENT peers (peer)+> 

<!ELEMENT peer (name,ip,as,as-set?,comments?,contact*, prefix-in?, prefix-out?, map-in?, map-out?, max-prefixes?)>
<!ATTLIST peer ix (sfinx|pouix|freeix|geix|panap) #REQUIRED>

<!ELEMENT comments (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT as (#PCDATA)>
<!ELEMENT as-set (#PCDATA)>
<!ELEMENT contact (#PCDATA)>

<!ELEMENT prefix-in (#PCDATA)>
<!ELEMENT prefix-out (#PCDATA)>
<!ELEMENT map-in (#PCDATA)>
<!ELEMENT map-out (#PCDATA)>

<!ELEMENT max-prefixes (#PCDATA)>

=== gitoyen/peering/peers.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE peers SYSTEM "peers.dtd">

<!-- Les "peers" de Gitoyen -->

<peers>
  <peer ix="sfinx">
    <name>RIPE</name>
    <ip>194.68.129.38</ip>
    <as>12654</as>
    <comments>A watcher:
    http://www.ripe.net/ripencc/pub-services/np/rrc02.html</comments>
    <prefix-in>peer-in</prefix-in> <!-- No longer spy-in, see the
    above page about their beacon -->
    <max-prefixes>2</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>Renater</name>
    <ip>194.68.129.102</ip>
    <as>2200</as>
   <contact>peering@renater.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>Renater</name>
    <ip>194.68.129.103</ip>
    <as>2200</as>
   <contact>peering@renater.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>Hivane</name>
    <ip>194.68.129.123</ip>
    <as>34019</as>
    <as-set>HIVANE</as-set>
    <contact>peering@hivane.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Absolight</name>
    <ip>194.68.129.121</ip>
    <as>29608</as>
    <as-set>W2MY</as-set>
    <contact>noc@w2my.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>RTL</name>
    <ip>194.68.129.132</ip>
    <as>44334</as>
    <as-set>RTL</as-set>
    <contact>david.ramahefason@rtl.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>Jet Multimedia</name>
    <ip>194.68.129.133</ip>
    <as>12566</as>
    <as-set>JETMULTIMEDIA</as-set>
    <contact>peering@jmsp.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>ARCOR</name>
    <ip>194.68.129.139</ip>
    <as>3209</as>
    <as-set>ARCORGLOBAL</as-set>
    <contact>peering@adm.arcor.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>OvaNet</name>
    <ip>194.68.129.142</ip>
    <as>29415</as>
    <as-set>OVANET</as-set>
    <contact>peering@ovanet.com</contact>
    <map-in>sfinx-backup-in</map-in>
  </peer>
  <peer ix="sfinx">
    <name>OVH</name>
    <ip>194.68.129.144</ip>
    <as>16276</as>
    <comments>http://www.ovh.net/</comments>
    <contact>ovh@ovh.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>CYREALIS</name>
    <ip>194.68.129.146</ip>
    <as>30972</as>
    <as-set>CYREALIS</as-set>
    <contact>peering@cyrealis.com</contact>
    <map-in>sfinx-backup-in</map-in>
  </peer>
  <peer ix="sfinx">
    <name>M-ROOT</name>
    <ip>194.68.129.148</ip>
    <as>7500</as>
    <contact>as7500@nspixp.wide.ap.jp</contact>
  </peer>
  <peer ix="sfinx">
    <name>F-ROOT</name>
    <ip>194.68.129.150</ip>
    <as>30126</as>
    <contact>peering@isc.org</contact>
  </peer>
  <peer ix="sfinx">
    <name>ARCOR</name>
    <ip>194.68.129.155</ip>
    <as>3209</as>
    <as-set>ARCORGLOBAL</as-set>
    <contact>peering@adm.arcor.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Viatel</name>
    <ip>194.68.129.156</ip>
    <as>8190</as>
    <as-set>VIATEL</as-set>
    <contact>peering@viatel.net</contact>
  </peer>
<!--
  <peer ix="sfinx">
    <name>Swisscom IP-Plus</name>
    <ip>194.68.129.159</ip>
    <as>3303</as>
    <contact>engineering@ip-plus.net</contact>
    <max-prefixes>2000</max-prefixes>
  </peer>
-->
  <peer ix="sfinx">
    <name>Andrexen</name>
    <ip>194.68.129.161</ip>
    <as>44583</as>
    <as-set>AS-ANDREXEN</as-set>
    <contact>peering@andrexen.com</contact>
    <max-prefixes>10</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>SWIPnet</name>
    <ip>194.68.129.162</ip>
    <as>1257</as>
    <as-set>SWIPNET</as-set>
    <contact>peering@swip.net</contact>
    <max-prefixes>1500</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>Cogent</name>
    <ip>194.68.129.164</ip>
    <as>174</as>
    <as-set>COGENT</as-set>
    <contact>peering@cogentco.com</contact>
    <max-prefixes>40000</max-prefixes>
  </peer>
  <peer ix="sfinx">
   <name>720degres</name>
   <ip>194.68.129.166</ip>
   <as>42937</as>
   <contact>peering@720.fr</contact>
   <max-prefixes>10</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>IDNET-UK</name>
    <ip>194.68.129.167</ip>
    <as>12496</as>
    <as-set>IDNETUK</as-set>
    <contact>matt@idnet.net.uk</contact>
  </peer>
  <peer ix="sfinx">
    <name>DyneGy Europe</name>
    <ip>194.68.129.169</ip>
    <as>12868</as>
    <as-set>DYNEGYEUROPE</as-set>
    <contact>peering@dynegyeurope.com</contact>
  </peer>
  <peer ix="sfinx">
    <name>Flag</name>
    <ip>194.68.129.170</ip>
    <as>15412</as>
    <as-set>GLOBAL</as-set>
    <contact>noc@flagtelecom.com</contact>
    <max-prefixes>5000</max-prefixes> <!-- Gros operateur
    international -->
  </peer>
  <peer ix="sfinx">
    <name>YACAST</name>
    <ip>194.68.129.171</ip>
    <as>24963</as>
    <as-set>YACAST</as-set>
    <contact>ldurand@yacast.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>Belgacom/Belbonet</name>
    <ip>194.68.129.173</ip>
    <as>6774</as>
    <as-set>BELBONETOPEERS</as-set>
    <contact>peering@belbone.be</contact>
    <max-prefixes>3000</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>Liazo</name>
    <ip>194.68.129.174</ip>
    <as>50618</as>
    <as-set>AS-LIAZO</as-set>
    <contact>info@liazo.fr</contact>
    <max-prefixes>100</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>Romania Data Systems</name>
    <ip>194.68.129.175</ip>
    <as>8708</as>
    <as-set>RDSNET</as-set>
    <contact>peering@rdsnet.ro</contact>
  </peer>
  <peer ix="sfinx">
    <name>PT Comunicacoes</name>
    <ip>194.68.129.176</ip>
    <as>8657</as>
    <as-set>CPRM</as-set>
    <contact>peering@cprm.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>9 Telecom</name>
    <ip>194.68.129.178</ip>
    <as>15557</as>
    <as-set>LDCOMNET</as-set>
    <contact>francois-xavier.thoret@neuf.com</contact>
  </peer>
  <peer ix="sfinx">
    <name>Nerim</name>
    <ip>194.68.129.181</ip>
    <as>13193</as>
    <contact>bouaziz@nerim.net</contact>
    <contact>mamanis@nerim.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Belnet</name>
    <ip>194.68.129.183</ip>
    <as>2611</as>
    <as-set>BELNET</as-set>
    <contact>noc@belnet.be</contact>
    <contact>peering@belnet.be</contact>
  </peer>
  <peer ix="sfinx">
    <name>e-i.com</name>
    <ip>194.68.129.184</ip>
    <as>8255</as>
  </peer>
  <peer ix="sfinx">
    <name>Completel</name>
    <ip>194.68.129.188</ip>
    <as>12670</as>
    <as-set>COMPLETELCUSTOMERS</as-set>
      <contact>j.blaisonneau@completel.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>Frontier Online</name>
    <ip>194.68.129.191</ip>
    <as>13049</as>
    <as-set>FRONTIER</as-set>
  </peer>
  <peer ix="sfinx">
    <name>Mgn</name>
    <ip>194.68.129.196</ip>
    <as>8784</as>
    <as-set>MGN</as-set>
    <contact>peering@mgn.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>NTL</name>
    <ip>194.68.129.197</ip>
    <as>5089</as>
    <contact>Mark.Warrington@ntl.com</contact>
  </peer>
  <peer ix="sfinx">
    <name>Above.net/Metromedia</name>
    <ip>194.68.129.201</ip>
    <as>6461</as>
    <contact>peering@above.net</contact>
    <max-prefixes>10000</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>Sunrise</name>
    <ip>194.68.129.213</ip>
    <as>6730</as>
    <as-set>GLOBAL</as-set>
    <comments>helpdesk@sunrise.net</comments>
    <contact>bgp@sunrise.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Globix</name>
    <ip>194.68.129.214</ip>
    <as>4513</as>
    <contact>netops@globix.net</contact>
  </peer>
  <peer ix="sfinx">
    <!-- MD5 y7GGt4541 -->
    <name>Pipex</name>
    <ip>194.68.129.215</ip>
    <as>5413</as>
    <as-set>PIPEX</as-set>
    <contact>peering@pipex.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Easynet</name>
    <ip>194.68.129.225</ip>
    <as>4589</as>
    <as-set>EASYNET</as-set>
    <contact>peering@easynet.fr</contact>
  </peer>
  <peer ix="sfinx">
    <name>Easynet</name>
    <ip>194.68.129.226</ip>
    <as>4589</as>
    <as-set>EASYNET</as-set>
    <contact>peering@easynet.fr</contact>
  </peer>
  <!-- Chello plus au Sfinx 2002-09-24 -->
  <peer ix="sfinx">
    <name>T-online/Grolier/Club-internet</name>
    <ip>194.68.129.219</ip>
    <as>5410</as>
    <contact>peering@t-online.fr</contact>
  </peer>
  <!-- 9 telecom disparu le 2002-10-07 -->
  <peer ix="sfinx">
    <name>Free/Proxad</name>
    <ip>194.68.129.223</ip>
    <as>12322</as>
    <as-set>PROXAD</as-set>
  </peer>
  <peer ix="sfinx">
    <name>Colt</name>
    <ip>194.68.129.224</ip>
    <as>8220</as>
    <contact>bmimeur@fr.colt.net</contact>
    <max-prefixes>3000</max-prefixes>
  </peer>
  <peer ix="sfinx">
    <name>Telefonica Deutschland</name>
    <ip>194.68.129.228</ip>
    <as>6805</as>
    <as-set>TDDE</as-set>
    <contact>Najam.Saquib@telefonica.de</contact>
    <!-- http://www.telefonica.de/peering/ -->
    <contact>peering@telefonica.de</contact>
  </peer>
  <peer ix="sfinx">
    <name>Internet-FR</name>
    <ip>194.68.129.230</ip>
    <as>8527</as>
    <contact>peering@internet-fr.net</contact>
  </peer>
<!--  fermeture du Sfinx La Bourse
  <peer ix="sfinx">
    <name>PSINet</name>
    <ip>194.68.129.231</ip>
    <as>3291</as>
    <as-set>PSINETEU</as-set>
    <contact>peering-help@psineteurope.com</contact>
    <max-prefixes>2000</max-prefixes>
  </peer> -->
  <peer ix="sfinx">
    <name>Libertysurf/Infonie/NoneNetwork</name>
    <ip>194.68.129.233</ip>
    <as>12876</as>
    <as-set>TISCALIFR</as-set>
    <contact>peering@libertysurf.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>AFNIC</name>
    <ip>194.68.129.238</ip>
    <as>2486</as>
  </peer>
  <peer ix="sfinx">
    <name>Ecritel</name>
    <ip>194.68.129.245</ip>
    <as>8304</as>
    <contact>fleduc@ecritel.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Noos</name>
    <ip>194.68.129.253</ip>
    <as>6678</as>
  </peer>
  <peer ix="sfinx">
    <name>Alionis</name>
    <ip>194.68.129.126</ip>
    <as>34997</as>
    <as-set>ALIONIS</as-set>
    <contact>noc@lionis.net</contact>
  </peer>
  <peer ix="sfinx">
    <name>Kazaar</name>
    <ip>194.68.129.120</ip>
    <as>35189</as>
    <as-set>KAZAAR</as-set>
    <contact>peering@as35189.net</contact>
  </peer>
  <peer ix="sfinx">
